# Generated by Django 6.0.1 on 2026-01-27 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Toll',
            fields=[
                ('toll_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('gate_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('gate_name', models.CharField(max_length=100)),
                ('gate_location', models.CharField(max_length=255)),
                ('tolls', models.ManyToManyField(related_name='gates', to='toll.toll')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_time', models.DateTimeField(auto_now_add=True)),
                ('fare_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toll.gate')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
