# Generated by Django 5.2.7 on 2026-01-30 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_date', models.DateTimeField(auto_now_add=True)),
                ('violation_type', models.CharField(max_length=100)),
                ('base_penalty', models.DecimalField(decimal_places=2, default=50.0, max_digits=10)),
                ('status', models.CharField(default='Unpaid', max_length=20)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
