# Generated by Django 6.0.1 on 2026-01-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelLog',
            fields=[
                ('detection_id', models.AutoField(primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_detections', to='toll.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('violation_no', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('current_violation_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='toll.trip')),
            ],
        ),
    ]
